COMPLIMENTS = [
  'Brilliant job!',
  'Outstanding work!',
  'This is truly above and beyond.',
  'We are thrilled to have you on our team and this is exactly why we need you.',
  'This is superb! I had no idea a document could look this good.',
  'We are so fortunate to have an innovator like you on our team.',
  'You set a high bar with this one.',
  'This showcases you are a role model and leader in our organization.',
  'Thank you!',
  'Good work, as always.',
  'Thanks for getting this done.',
  'You are a lifesaver.',
  'Thanks for your help today.',
  'Thanks for your good work this week.',
  'Thanks for stepping up and getting this done for us.',
  'I don’t know what I would do without you.',
  'Perfect!',
  'Thanks, this is exactly what I was looking for.',
  'Wonderful, this is more than I expected.',
  'I appreciate your critical thinking around this project.',
  'Well done—and ahead of deadline too!',
  'You are such a team player.',
  'You are so creative—I always love getting your perspective on things.',
  'You consistently bring your all and I truly appreciate that.',
  'I am so proud to have you part of my team.'
]
