COMPLIMENTS = [
'Brilliant job!',
'Outstanding work!',
'Great job!',
'Now you\'ve got it! Awesome!',
'You have a lot of talent!',
'Superior!',
'Fantastic!',
'Right on!',
'Outstanding!',
'You\'re the best!',
'Nice job',
'That\'s a commendable job.',
'Wonderful!',
'Fabulous!',
'You did it!',
'Good going!',
'You\'re great!',
'Groovy!',
'You\'re good at this.',
'Good job!',
'Good work!',
'Keep up the good work!',
'Clever!',
'Incredible!',
'Impressive!',
'Nice work.',
'I\'m proud of you.',
'Bravo!',
':clap:',
'Hot diggity dog!',
'Terrific!',
'Thank you.',
'Great!',
'Great!',
'You really outdid yourself!',
'You are very intelligent!',
'Cool!',
':dank-grapes:',
':party-parrot:',
':thumbsup:',
':grinning:',
':smile:',
':baymax:',
'You\'re doing very well!',
'You\'re doing quite well.',
'You did very well.',
'You did it!',
':holt: Steve Holt!']

SHIP_SYMBOLS = [
  ":ship:",
  ":shipit:",
  ":merge:",
  ":chipmunk:",
  ":rocket:",
  ":boat:",
  ":boaty:"
]
